[package]
name = "cut-expenses"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.7.0", features = ["serde", "v4"] }
diesel = { version = "2.1.0", features = ["postgres", "uuid"] }
dotenv = "0.15.0"